### ISSUE TITLE
Obj-C example typo

### ISSUE THREAD

**Issue by phoboslab** [color-tv/Color-tvOS-SDK#8]
From the `readme.md`:
```objc
vc.adCompleted = ^{
    dispatch_async(dispatch_get_main_queue(), ^{
        [self dismissViewControllerAnimated:YES completion:nil];
    });
};
```
This tripped me up for a minute. I believe the `dismissViewControllerAnimated` should be called on `vc`, not on `self`, right? I.e.

```objc
[vc dismissViewControllerAnimated:YES completion:nil];
```

**Comment by mciuba** [comment]
It's not a typo in this case. I understand that it might be a bit unintuitive, though. Let's see what happens there. First, we present `vc` modally on `self`:

```
            dispatch_async(dispatch_get_main_queue(), ^{            
                [self presentViewController:vc animated:YES completion:^{
                   
                }];
            });
```

Then, when the ad completes, we have to dismiss `vc`. And the [documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/index.html#//apple_ref/occ/instm/UIViewController/dismissViewControllerAnimated:completion:) says that 

> The presenting view controller is responsible for dismissing the view controller it presented. 

That's why we call `dismissViewControllerAnimated:completion:` on `self` (which is the presenting view controller) and not on `vc`.

I hope it's clear now.

**Comment by phoboslab** [comment]
I'm sorry, I should've looked in the docs first. For some reason it didn't work me (the ad view was still shown) when I called `dismissViewControllerAnimated` on the presenting ViewController. Not sure why.

In any case, the docs also say:
>  If you call this method on the presented view controller itself, UIKit asks the presenting view controller to handle the dismissal.

So I should be fine, calling it on `vc`.

Thanks!
